<a href="https://colab.research.google.com/github/poppvk935/Astrophysics-Deep-Learning/blob/main/Intro_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import torch
import numpy as np

**Lists**

In [6]:
mylist = [1, 2, 3, 4]
mylist

[1, 2, 3, 4]

NUMPY **Arrays**

In [7]:
np1 = np.random.rand(3,4)
np1


array([[0.5487835 , 0.6301235 , 0.90932569, 0.12366464],
       [0.67649614, 0.41844016, 0.84451682, 0.57027581],
       [0.22025308, 0.12422938, 0.18784387, 0.01346706]])

In [9]:
np1.dtype

dtype('float64')

**Tensors**


In [14]:
tensor_2d = torch.randn(3, 4)
tensor_2d
tensor_2d.dtype

torch.float32

In [11]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.5488, 0.6301, 0.9093, 0.1237],
        [0.6765, 0.4184, 0.8445, 0.5703],
        [0.2203, 0.1242, 0.1878, 0.0135]], dtype=torch.float64)