<a href="https://colab.research.google.com/github/poppvk935/Astrophysics-Deep-Learning/blob/Deep-Learning-with-PyTorch/tensor_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Tensor Math Operations**



*   Add, subtract, multiply, divide, remainders, exponents
*  Shorthand and longhand
*  Reassignment



In [22]:
import torch
import numpy as np

In [23]:
tensor_a = torch.tensor([1, 2, 3, 4])
tensor_b = torch.tensor([5, 6, 7, 8])

In [24]:
#Addition

print(tensor_a + tensor_b)

print("[1+5, 2+6, 3+7, 4+8]")

tensor([ 6,  8, 10, 12])
[1+5, 2+6, 3+7, 4+8]


In [25]:
#Addition longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [26]:
#Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [27]:
#Subtraction Function
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [28]:
#multiplication
print(tensor_a * tensor_b)

print(torch.mul(tensor_a, tensor_b))

tensor([ 5, 12, 21, 32])
tensor([ 5, 12, 21, 32])


In [29]:
#division

print(tensor_b/tensor_a)

print(torch.div(tensor_b, tensor_a))

tensor([5.0000, 3.0000, 2.3333, 2.0000])
tensor([5.0000, 3.0000, 2.3333, 2.0000])


In [30]:
#Remainder

print(tensor_b % tensor_a)

print(torch.remainder(tensor_b, tensor_a))

tensor([0, 0, 1, 0])
tensor([0, 0, 1, 0])


In [31]:
#Exponents

print(tensor_a ** tensor_b)

print(pow(tensor_a, tensor_b))



tensor([    1,    64,  2187, 65536])
tensor([    1,    64,  2187, 65536])


In [32]:
#another way to write longhand
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [33]:
#Reassignment

tensor_a.add_(tensor_b)
print(tensor_a)
#reassign this to tensor a

tensor([ 6,  8, 10, 12])
