<a href="https://colab.research.google.com/github/poppvk935/Astrophysics-Deep-Learning/blob/main/tensor_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [42]:
import torch

In [43]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
#Reshape data
    #Use reshape and view
my_torch = my_torch.reshape(2,5)
my_torch
#my_torch = my_torch.reshape(2,6) will not work because the original tensor of 10 values
#cannot be equally split into 2 groups of 6


tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [45]:
#Reshape if we don't know the number of items
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
#Do this with -1 as the second parameter of reshape
my_torch2 = my_torch2.reshape(2,-1)
my_torch2
#your first parameter still has to be divisible by your number of items
#or else you will get a runtime error, should say what the input size is

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [47]:
#can do the same thing in the opposite direction
my_torch2 = my_torch2.reshape(-1, 5)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [48]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [50]:
#reshape and view will update
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
my_torch6 = my_torch5.reshape(2, 5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [52]:
my_torch5[1] = 4141
my_torch5

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [53]:
my_torch6

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [54]:
#slices

my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
#grab a specific item
my_torch7[7]
#grabs a scalar of 7

tensor(7)

In [56]:
#Grab slice
my_torch8 = my_torch7.reshape(5, 2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [57]:
my_torch8[:, 1]

tensor([1, 3, 5, 7, 9])

In [60]:
#return column
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])